# SAM configuration file for different environments
version = 0.1

[default]
[default.global]
[default.global.parameters]
stack_name = "anymouse-dev"

[default.build]
[default.build.parameters]
cached = true
parallel = true

[default.deploy]
[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
s3_prefix = "anymouse"
region = "us-east-1"
image_repositories = []

[staging]
[staging.global]
[staging.global.parameters]
stack_name = "anymouse-staging"

[staging.deploy]
[staging.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
s3_prefix = "anymouse"
region = "us-east-1"
parameter_overrides = "Stage=staging"

[prod]
[prod.global]
[prod.global.parameters]
stack_name = "anymouse-prod"

[prod.deploy]
[prod.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "anymouse"
region = "us-east-1"
parameter_overrides = "Stage=prod"